### ISSUE TITLE
Question: references and code style

### ISSUE THREAD

**Issue by jeannekamikaze** [bjz/cgmath-rs#121]
I don't quite follow your logic of when to pass arguments by value and when to pass by reference. For example, on the one hand you have:

```Rust
fn look_at(dir: &Vector3<S>, up: &Vector3<S>) -> Matrix3<S>
```

which seems reasonable enough, although passing two Vector3 by value shouldn't be too expensive. However, on the other hand you have:

```Rust
fn new(left: Plane<S>, right: Plane<S>, bottom: Plane<S>, top: Plane<S>, near: Plane<S>, far: Plane<S>) -> Frustum<S>
```

which, as far as I understand, will imply the copy of 6 planes to construct a Frustum.

Could you shed some light into this?
Thanks.

**Comment by bjz** [comment]
We are now moving to a by-value style - see #247
