### ISSUE TITLE
Proposal: Triangles

### ISSUE THREAD

**Issue by jeannekamikaze** [bjz/cgmath-rs#122]
Adding triangles to the library could be useful to then provide built-in functions such as plane-triangle and frustum-triangle intersections. However, the exact representation of a triangle is always application-dependent: it could be 3 vertices, 3 vertices and a normal, 3 indices into some array of vertices, etc. For this reason, in the application I am currently writing, I have written a `Triangle` trait to abstract away particular triangle representations:

```Rust
pub trait Triangle<S> {
    fn p0 (&self) -> Point3<S>;
    fn p1 (&self) -> Point3<S>;
    fn p2 (&self) -> Point3<S>;
}
```

Once the trait is set up, you can provide a whole bunch of useful functions:

```Rust
pub fn supporting_plane<S: BaseFloat> (t: &Triangle<S>) -> Option<Plane<S>>
```

```Rust
pub enum PlaneIntersection {
    Front,
    Back,
    Intersecting,
    Containing
}

pub fn intersect<S: Num + BaseFloat> (p: &Plane<S>, t: &Triangle<S>) -> PlaneIntersection
```

When the client code wants to  use these functions, they simply write a `Triangle` implementation for their particular triangle representation:

```Rust
struct SimpleTriangle {
    _p0: Point3<f32>,
    _p1: Point3<f32>,
    _p2: Point3<f32>
}

impl Triangle<f32> for SimpleTriangle {
    fn p0 (&self) -> Point3<f32> { self._p0 }
    fn p1 (&self) -> Point3<f32> { self._p1 }
    fn p2 (&self) -> Point3<f32> { self._p2 }
}
```

and then they are ready to roll.

What do you think about integrating something like this into cgmath?

**Comment by bjz** [comment]
Collision detection was moved to [collision-rs](https://github.com/csherratt/collision-rs) in #245. See #244 for more details. Closing as won't-fix.
