### ISSUE TITLE
Provide GLM interface

### ISSUE THREAD

**Issue by kvark** [bjz/cgmath-rs#169]
GLM is well known. It would be nice to have a compatible interface.

We don't need to change existing code, we can just add `glm` module with some functions, so that `glm::rotate`, for example, produces a matching `Matrix4`.

Edit: I don't have much GLM experience, so maybe someone else wants to try this out?

**Comment by cmr** [comment]
That'd be pretty nice, GLM has a great API.


On Mon, Feb 9, 2015, at 20:27, Dzmitry Malyshau wrote:
> GLM is well known. It would be nice to have a compatible interface.


> We don't need to change existing code, we can just add glm module with
> some functions, so that glm::rotate, for example, produces a matching
> Matrix4.


> — Reply to this email directly or view it on GitHub[1].

>



Links:

  1. https://github.com/bjz/cgmath-rs/issues/169

**Comment by bjz** [comment]
Part of the challenge with replicating a GLM API would be the fact that it does so much overloading and template stuff.

**Comment by bjz** [comment]
As far as I can see, we can't really do this with Rust's type system. Closing. If there was a more concrete proposal, it'd be easier to evaluate, however.
