### ISSUE TITLE
Update lib with associated types.

### ISSUE THREAD

**Issue by bjz** [bjz/cgmath-rs#197]
`#[old_impl_check]` was recently removed:

~~~
src/line.rs:31:1: 31:18 error: The attribute `old_impl_check` is currently unknown to the the compiler and may have meaning added to it in the future
src/line.rs:31 #[old_impl_check]
               ^~~~~~~~~~~~~~~~~
src/line.rs:31:18: 31:18 help: add #![feature(custom_attribute)] to the crate attributes to enable
src/ray.rs:28:1: 28:18 error: The attribute `old_impl_check` is currently unknown to the the compiler and may have meaning added to it in the future
src/ray.rs:28 #[old_impl_check]
              ^~~~~~~~~~~~~~~~~
src/ray.rs:28:18: 28:18 help: add #![feature(custom_attribute)] to the crate attributes to enable
error: aborting due to 2 previous errors
~~~

Removing the attributes results in:

~~~
src/line.rs:31:6: 31:7 error: the type parameter `S` is not constrained by the impl trait, self type, or predicates [E0207]
src/line.rs:31 impl<S: BaseNum, V: Vector<S>, P: Point<S, V>>  Line<P> {
                    ^
src/line.rs:31:18: 31:19 error: the type parameter `V` is not constrained by the impl trait, self type, or predicates [E0207]
src/line.rs:31 impl<S: BaseNum, V: Vector<S>, P: Point<S, V>>  Line<P> {
                                ^
src/ray.rs:28:6: 28:7 error: the type parameter `S` is not constrained by the impl trait, self type, or predicates [E0207]
src/ray.rs:28 impl<S: BaseNum, V: Vector<S>, P: Point<S, V>> Ray<P, V> {
                   ^
error: aborting due to 3 previous errors
~~~

Apparently cgmath needs associated types from the ground up to solve this problem.

**Comment by kvark** [comment]
Not sure if it's got to be associated types though. Another way to approach this is to have `S` as an explicit generic parameters to stuff, like `Line<S, P>` instead of `Line<P>`.

**Comment by csherratt** [comment]
Is anyone actively looking at this problem?

**Comment by kvark** [comment]
Not at the moment, but I sure will as soon as I need to update rustc. Please take care of it if you can/will.

**Comment by csherratt** [comment]
I keep getting ICE Errors when I try to move to associated types.

There might be a hackish way to make it worth using `PhantomData`, but that is ugly and breaks everything downstream.

**Comment by kvark** [comment]
@csherratt do you need help?
Also, why does it have to be associated types?

**Comment by csherratt** [comment]
https://github.com/bjz/cgmath-rs/blob/master/src/line.rs#L32 Is a good example of us using the old type system when Associated types would work much better. The fact that the `Vector` is supplied here is because it is needed as a return type in the `Point` trait. Which is textbook use for associated types.

The entire library is actually pretty difficult to update trait by trait. There is so many cross pollination that you can't actually remove `line.rs` for the sake of getting things to compile.

If someone else knows how to tackle this, be my guest. It's going to be a large change.

**Comment by csherratt** [comment]
This will fix the build break https://github.com/bjz/cgmath-rs/pull/198 But I would much rather migrate to associated types. It just might be better to do so without the pressure of having master broken.

**Comment by bjz** [comment]
I believe this is fixed...
