### ISSUE TITLE
Point-point arithmetic should be available

### ISSUE THREAD

**Issue by burtonageo** [bjz/cgmath-rs#212]
It would be very useful (for me) if you could use standard operators with points,
that operated on each element piecewise (e.g. P1 {3, 1} + P2 {2, 2} = P3 {5, 3}).

 To do this would require changing the point interface to include the function:
 
    fn add_p(&self, p: &Self) -> Self;

as well as the optional functions:

    fn add_self_p(&mut self, p: &Self);
    fn sub_self_p(&mut self, p: &Self);

And to change the signature of ```sub_p``` to:

    fn sub_p(&self, p: &Self) -> Self;

The old behaviour of ```sub_p``` could be achieved by chaining it with a ```to_vec()``` call, or
(if it's a really common operation), a new method could be added to the interface.

**Comment by kvark** [comment]
Sorry, point addition doesn't make sense. That's what vectors are for.
