### ISSUE TITLE
Replace the branch master by branch rust-1.0

### ISSUE THREAD

**Issue by tomaka** [bjz/cgmath-rs#213]
The branch rust-1.0 is what is on crates.io and is what people use I belive.

**Comment by kvark** [comment]
I dunno, I'm using the master. Who is using cgmath on rust-1.0?

**Comment by tomaka** [comment]
cgmath has around 50 to 200 downloads per day. So these people use what is on the rust-1.0 branch.

**Comment by kvark** [comment]
hmm, ok. How about: 'rust-1.0 -> master', 'master -> nightly' ?

**Comment by tomaka** [comment]
Why would we even need a "nightly" branch? There aren't any unstable functions in the std that would bring a lot of benefits to cgmath.

**Comment by kvark** [comment]
As long as the master builds on nightly, and we don't need to diverge - sure, we can get away without branching.
