### ISSUE TITLE
Why not references in the `Intersect` tuples?

### ISSUE THREAD

**Issue by jarrett** [bjz/cgmath-rs#220]
Right now, the `Intersect` trait is implemented for tuples of values, like this:

    (Sphere<S>, Ray3<S>)

The problem is that you have to copy the values if you want to use them after testing the intersection. For example:

    let inter = (my_sphere.clone(), my_ray.clone().intersection();
    some_other_function(&my_sphere, &my_ray);

To avoid that copying, could we implement `Intersect` for tuples of references instead? Like this:

    (&Sphere<S>, &Ray3<S>)

Or perhaps tuples of references and tuples of values could both be supported.

**Comment by kvark** [comment]
:+1:

**Comment by bjz** [comment]
Collision detection was moved to [collision-rs](https://github.com/csherratt/collision-rs) in #245. See #244 for more details. Closing as won't-fix.
