### ISSUE TITLE
ToX -> Into<X>

### ISSUE THREAD

**Issue by Yamakaky** [bjz/cgmath-rs#225]
Instead of the ToX traits, did you consider implementing From<X> ?

**Comment by cmr** [comment]
Those traits didn't exist at the time. It would probably be fine, would
need to see how the coherence works out


On Sat, Aug 22, 2015, at 06:57, Yamakaky wrote:
> Instead of the ToX traits, did you consider implementing Into
> ans From ?


> — Reply to this email directly or view it on GitHub[1].


>

/cmr



Links:

  1. https://github.com/bjz/cgmath-rs/issues/225

**Comment by tomaka** [comment]
There have already been some changes towards `From`. What's missing is people making the changes.

**Comment by Yamakaky** [comment]
Wow, in fact the doc http://www.rust-ci.org/bjz/cgmath-rs/doc/cgmath/index.html doesn't seem to be accurate, for example I can't find ToMatrix2 in master.

**Comment by cmr** [comment]
rust-ci is out of date, we should really setup a gh-pages with travis...

**Comment by bjz** [comment]
As of #229, the docs now get pushed to gh-pages
