### ISSUE TITLE
Add a camera

### ISSUE THREAD

**Issue by Yamakaky** [bjz/cgmath-rs#226]
Did you consider adding a Camera ? It would have a position, yaw, pitch, roll, view_matrix() and setters so -pi/2 < pitch < pi/2 and 0 < yaw < 2pi. Nearly every 3d program uses a camera. It could also be a function like `cgmath::perspective` : `fn view_matrix(eye: Point3, yaw: Rad, pitch: Rad, roll: Rad) -> Matrix4`

Edit: I know about `look_at`, but I don't find it really useful to implement a fps camera.

**Comment by kvark** [comment]
Most games need cameras, but the way they use it is entirely different. Some prefer quaternions, some yaw+pitch+roll, some may work with matrices. Considering the absence of a single true way to represent a camera, and the fact that the camera is a higher level concept, I'd vote against trying to include it here. Have a look at [cam](https://github.com/PistonDevelopers/cam) and [camera_controllers](https://github.com/PistonDevelopers/camera_controllers) instead.

**Comment by Yamakaky** [comment]
Maybe then a fonction converting up right forward to a view matrix ?

**Comment by kvark** [comment]
This function is called matrix inversion ;)

Up/Right/Forward are the Y, X, Z axis of the camera basis. A view matrix is supposed to transform from world space into camera space, thus it is just the unversed basis. If the basis is orthogonal, then the inversion is simply a transposition.

Thus, I don't see much use in another transposition function. Let's hear what other contributors think. Summoning @bvssvni and @csherratt .

**Comment by Yamakaky** [comment]
up right forward position*

**Comment by kvark** [comment]
Ah right, the position...
We have a [look_at](https://github.com/bjz/cgmath-rs/blob/master/src/transform.rs#L38) that helps. Perhaps, we could have another method inside `Transform` trait to do your thing.

**Comment by csherratt** [comment]
@Yamakaky does this help https://github.com/csherratt/camera/blob/master/src/lib.rs ? I use it my engine to do a FPS style control see https://github.com/whiske-rs/whiske/blob/master/src/no_clip/src/lib.rs

Both need polish of course.

**Comment by bjz** [comment]
I think the right place for this is in a separate library. Closing as won't fix.
