### ISSUE TITLE
RFC: Remove collision types and traits

### ISSUE THREAD

**Issue by bjz** [bjz/cgmath-rs#244]
These are incomplete and complicate the API. I don't see them being fleshed out any time soon. Perhaps another library could take up the slack. Thoughts?

Proposed for removal:

- `Aabb`, `Aabb2`, `Aabb3`
- `Bound`
- `Cylinder`
- `Frustum`, `FrustumPoints`
- `Intersect`
- `Line`
- `Ray`
- `Obb2`, `Obb3`
- `Plane`
- `Sphere`

**Comment by kvark** [comment]
No problem. Will move somewhere else, since `gfx_scene` uses those.

**Comment by bjz** [comment]
@csherratt has his [collision-rs library](https://github.com/csherratt/collision-rs) - maybe there?

**Comment by csherratt** [comment]
I have mostly abandoned work on collision-rs, but I don't see a reason why we can't revive it and move these traits to it.

**Comment by csherratt** [comment]
Not PR since it will destroy the history of `collision-rs` (github hates this) but I plan on merging https://github.com/csherratt/collision-rs/tree/merge_cgmath into master if you think it is a good place to live.

**Comment by bjz** [comment]
Looks good @csherratt! Let's merge #245 once your thing is published.

**Comment by bjz** [comment]
I've decided to merge the PR - we'll just hold off on publishing until the collision-rs is published

**Comment by bjz** [comment]
Reopening - we'll close this once @csherratt has done his thing.

**Comment by csherratt** [comment]
Done! \o/
