### ISSUE TITLE
API should work by-value rather than by-reference

### ISSUE THREAD

**Issue by jpernst** [bjz/cgmath-rs#247]
Modern architectures like x64 perform all floating-point math in SIMD registers, which typically have a width of at least 128bit. This is large enough to store an entire Vec4 as one register, which enables efficient pass-by-value semantics when performing vector math. Floating point math is most efficient when the values being manipulated stay within the SIMD registers as long as possible without being spilled to the stack or RAM. Using a by-value API allows the compiler to ensure this is the case.

Here's a good article describing this: http://www.gamasutra.com/view/feature/132636/designing_fast_crossplatform_simd_.php

Further, a by-value API improves ergonomics as values can be treated as primitives, which enables the natural expressions that primitives enjoy.

Finally, doing this will allow for potential further SIMD optimizations as rust gains support for it. SIMD types should always be treated by value, as by-reference semantics require them to be flushed out of the registers and back into RAM.

## Todo

- [ ] `Quaternion::magnitude`
- [x] `Quaternion * Vector3`
- [x] `Quaternion + Quaternion`
- [x] `Quaternion - Quaternion`
- [x] `Quaternion * Quaternion`
- [ ] And more...

**Comment by bjz** [comment]
How does this work for two and three dimensional vectors?

**Comment by jpernst** [comment]
The remaining space in the register is simply ignored, similar to doing a 32bit integer add on a 64bit machine.

**Comment by bjz** [comment]
Do you think predicates like and functions that return a scalar value (like `length`) should also be taken by-value?

**Comment by jpernst** [comment]
Yes, I'd suggest all functions have a by-value version. It's possible the full gains won't be realized until rust's SIMD support lands, but any function that works only by-ref will be an impediment to later SIMD efforts. I'd recommend by-value be the default choice, with a possible by-ref fallback if benchmarking indicates the pre-SIMD version is significantly slower for some reason. The by-value and by-ref APIs could even co-exist for a time.

**Comment by tomaka** [comment]
All types are `Copy`, so the change should be transparent from an API point of view.

**Comment by bjz** [comment]
So matrices should be by-value too?

Also, how useful are the mutating methods? The take self by mutable ref.

**Comment by jpernst** [comment]
Matrices should also be by-value, yes. Once SIMD support lands we'll be able to enforce that a matrix is only 4 registers, but before that we're at the mercy of LLVM's codegen. It might be worth benchmarking it or inspecting the compiled output in the meantime. Eventually, though, they will need to be by-value.

Directly reading or mutating a single element of a SIMD vector is already a (comparatively) costly operation that involves flushing the register, so it's less important that it be by-value since you're paying the cost anyway. Those can probably just be left as is for now, since a well designed algorithm will keep the values inside the registers as long as possible and only read out elements at the very end.

**Comment by bjz** [comment]
Added a todo list - need to do more checking of the library though

**Comment by porky11** [comment]
it may be nice to also have a reference version for all operators and other traits like they are defined in stdlib too, so it would be easier to handle Vectors of types that are not copyable.
An alternative may be disallowing uncopyable types in Vectors, since this is only meant for CG
