### ISSUE TITLE
FPS Camera

### ISSUE THREAD

**Issue by jellytux** [bjz/cgmath-rs#266]
How to implement FPS camera?

**Comment by kvark** [comment]
It's a method of the `Transform` trait. Do you have it in scope? You could do: `let view: cgmath::Matrix4<_> = cgmath::Transform::look_at(...);`

**Comment by jellytux** [comment]
I am not quite following, 
```rust
let view = cgmath::Matrix4::look_at(&eye, &center, &up);
```
Is working no errors whatsoever, `cgmath::Matrix4<_> = cgmath::Transform::look_at(...);` this didn't work tried it. Yes, I have Transform in scope:
```
src/main.rs:144:40: 144:66 error: the trait `cgmath::transform::Transform<f32, cgmath::vector::Vector3<f32>, cgmath::point::Point3<f32>>` is not implemented for the type `cgmath::matrix::Matrix4<_>` [E0277]
src/main.rs:144         let view: cgmath::Matrix4<_> = cgmath::Transform::look_at(&eye, &center, &up);
```

Also here's a youtube video ( https://youtu.be/SCEtqBBgk3I ) where I make very long mouse movements left and right slowly. It is spinning out of control instead of moving, that's what I mean by "not working as it should".

I used `view_matrix` function that glium crate has on their tutorial (http://tomaka.github.io/glium/book/tuto-12-camera.html) and it worked partially (note the weird skewing/distortion): https://www.youtube.com/watch?v=1ky9cuysrqk

That's why I thought I should use the `look_at` instead but as you can see from the first Youtube video it doesn't :(

**Comment by bjz** [comment]
What, why does this have an empty title? [What happened here](https://xkcd.com/979/)?

**Comment by kvark** [comment]
Huh, weird. I also received another comment (prior to closing) that has probably got deleted here

**Comment by bjz** [comment]
@jellytux: if your problem was solved, would you mind posting the solution for the benefit of others? Would be most appreciated! :)

**Comment by jellytux** [comment]
Solution:
[1] Watch this:
https://www.youtube.com/watch?v=-tonZsbHty8
[2] Read this:
http://www.3dgep.com/understanding-the-view-matrix/
[3 optional] Also this:
http://www.3dgep.com/understanding-quaternions/
[4 optional] For a mathematical understanding of the perspective matrix read this:
http://www.songho.ca/opengl/gl_projectionmatrix.html
