### ISSUE TITLE
AABB collision detection could be faster

### ISSUE THREAD

**Issue by HeroesGrave** [bjz/cgmath-rs#98]
For a 2D AABB, 4 checks are being performed to determine if a point is inside.

This can be cut down to 2 checks, at the cost of the internals getting a little bit switched around.
Instead of storing AABBs as 2 points, they can be stored as a centre and extent:

```rust
pub struct Aabb2<S> {
    centre: Point<S>,
    extent: Vector2<S>,
}
```
(I don't know what the functional difference is between Points and Vectors, but I think it doesn't matter too much)

With that, the collision checking becomes a bit more efficient, as you can take the difference of 2 centres, and compare it to the sum of the extents, effectively halving the checks required. (I wrote a quick and dirty example [here](http://is.gd/XNKOEn)). The same idea can be applied to aabb-point collision by giving assuming points have an extent of zero.

The reason I haven't put this straight into a pull request is that it fundamentally changes the internals of aabbs in a way that may confuse people who aren't aware of the change. Also, the lack of an `abs()` method for integer types may require some sort of workaround, which I am not sure of.

Most of the information is in the example. (http://is.gd/XNKOEn)

**Comment by bjz** [comment]
Collision detection was moved to [collision-rs](https://github.com/csherratt/collision-rs) in #245. See #244 for more details. Closing as won't-fix.
